Steps for test-169 were added. Issue#181
filetrust/icap-management-ui-tests pull request #182
Opened 2021-01-19 18:12 UTC by vfedrunov

A few tests with number '@TEST-169' exist
The first of them works 
![image](https://user-images.githubusercontent.com/50262512/105075574-ea085000-5a57-11eb-84c2-50d938187827.png)

Other tests in '@request-history-file-detail-view' don't have enough test data. But they ready to run after adding the test data

2021-01-19 18:46 UTC, NadHodeGW requested changes
Please see comment in feature file

2021-01-19 18:46 UTC, NadHodeGW commented on specs/features/request-history-file-detail-view.feature
> +            | 11aded86-a598-4c42-a8c8-094c01012ae0 | 97976586 | 18/01/2021 19:00 PM | 18/01/2021 23:59 PM |
The first one can be a existing file but all others should use a new file, so process a new file and view that after filtering the log using the 1 hour selection

2021-01-20 14:37 UTC, NadHodeGW commented on specs/features/request-history-file-detail-view.feature
> +            | 11aded86-a598-4c42-a8c8-094c01012ae0 | 97976586 | 18/01/2021 19:00 PM | 18/01/2021 23:59 PM |
@vfedrunov please use the latest master to use the updated file-detail-view.feature

2021-01-21 10:45 UTC, vfedrunov commented
TEST-169, TEST-169_2 were passed

@NadHodeGW please take a look:
No 'Embedded file content present.' item and no 'First XREF table entry malformed and will be regenerated' item are displayed in the detailed results
File id: 10826ad3-2971-4d93-bab2-96e209f1a730, 38101dc7-8c11-4245-b7ad-0ea8c17f98fa
![image](https://user-images.githubusercontent.com/50262512/105340374-c9510f00-5bab-11eb-8fd1-cf8f87289fe3.png)

2021-01-21 15:54 UTC, NadHodeGW commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
we don't need the type and risk it adds complication for not much; you just need to submit a file get the fileId, search for that id in the log and open the record. please leave the 2nd step as it was:
 And The transaction is available in the transaction log

2021-01-21 16:00 UTC, NadHodeGW commented
@vfedrunov please use file: 'EmbeddedFile.pdf' then

2021-01-22 08:53 UTC, vfedrunov commented
> @vfedrunov please use file: 'EmbeddedFile.pdf' then

@NadHodeGW 'EmbeddedFile.pdf' is absent in '/src/data/input/' in master, could you share this file?
https://github.com/filetrust/icap-management-ui-tests/tree/master/src/data/input

2021-01-22 08:54 UTC, vfedrunov commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
The file id is absent in the icap response when the file was unmodified

```
ICAP server:icap-client-qa-main.uksouth.cloudapp.azure.com, ip:192.168.65.3, port:1344

No modification needed (Allow 204 response)

ICAP HEADERS:
	ICAP/1.0 204 Unmodified
	Server: C-ICAP/0.5.7
	Connection: keep-alive
	ISTag: CI0001-2.1.1

```

2021-01-22 18:07 UTC, NadHodeGW commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
yes, no file is returned if NTFS is on relay and no id returns for 204 responses

2021-01-25 08:59 UTC, vfedrunov commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
File is returned and contains the id. But no id is returned in the response and logs. 
I can try to use the id from the file if it is not a bug, that the file is returned in this case.

![image](https://user-images.githubusercontent.com/50262512/105683490-ae3f1180-5ec1-11eb-971a-d83f7caee415.png)

2021-01-25 09:11 UTC, vfedrunov commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
`ICAP server:icap-client-qa-main.uksouth.cloudapp.azure.com, ip:192.168.65.3, port:1344


ICAP HEADERS:
	ICAP/1.0 200 OK
	Server: C-ICAP/0.5.7
	Connection: keep-alive
	ISTag: CI0001-2.1.1
	Encapsulated: res-hdr=0, res-body=235

RESPMOD HEADERS:
	HTTP/1.0 403 Forbidden
	Server: C-ICAP
	Connection: close
	Content-Type: text/html
	X-Adaptation-File-Id: ca05f0ef-dbec-432d-854f-d55d866507af
	Via: ICAP/1.0 mvp-icap-service-6c7c5f94-jqkhz (C-ICAP/0.5.7 Glasswall Rebuild service )

`
The id is available in the log also today

2021-01-25 12:44 UTC, NadHodeGW commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
it all depends on the policy in use. you need to check the policy applied.

2021-01-25 14:30 UTC, vfedrunov commented on specs/features/request-history-file-detail-view.feature
> +            | structuralIssues.xlsx | End of stream 'wsSortMap1.xml' not reached | Xlsx | Allowed by Policy |
@NadHodeGW 
Sorry, I cannot see the policy in the preconditions in the feature file. As far as I remember I should not update feature files, should I?

2021-01-26 19:50 UTC, vfedrunov commented
`FAIL  | 3 passed, 1 failed   // 2m`
The fail reason is 'No Content Management Policy is displayed!'
![image](https://user-images.githubusercontent.com/50262512/105896969-88129200-5fe5-11eb-9c3b-2fe552f17907.png)

2021-01-27 14:17 UTC, NadHodeGW approved these changes

2021-01-27 14:17 UTC, merged