Multiple updates across files(readme, package, ncfs tests, test 212, file result view,
filetrust/icap-management-ui-tests pull request #187
Opened 2021-01-29 18:42 UTC by NadHodeGW

2021-02-02 13:34 UTC, asloman commented on specs/features/request-history-file-detail-view.feature
> +    @TEST-169_2
Two tests called TEST-169_2

2021-02-02 13:39 UTC, asloman commented on specs/features/user-session-admin.feature
> +            |          |          |
Is this due to unsure what accounts are set up?

2021-02-02 14:08 UTC, asloman requested changes
Request History file detail feature has 2 tests called 169_2
Test login has blank username password? Are these meant to be or due to not having 1 consistent account set up yet?

2021-02-03 11:59 UTC, NadHodeGW commented on specs/features/user-session-admin.feature
> +            |          |          |
this is updated in next pr

2021-02-03 13:18 UTC, asloman approved these changes

2021-02-03 13:20 UTC, merged