file types process with icap client, history count selection
filetrust/icap-management-ui-tests pull request #196
Opened 2021-02-11 15:16 UTC by NadHodeGW

2021-02-11 15:37 UTC, werzl requested changes

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +const { I, policyPage, filedropPage, requesthistoryPage, sharepoint,icapclient } = inject();
```suggestion
const { I, policyPage, filedropPage, requesthistoryPage, sharepoint, icapclient } = inject();
```

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +    var outputPath = './output/downloads'
Just a suggestion: because you're using the same value for outputPath, and it's not likely to change, you could declare `const outputPath = './output/downloads';` at the top of the file.

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
```suggestion
  await icapclient.processFiles(inPath, outputPath);
```

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
```suggestion
  await icapclient.processFiles(inPath, outputPath);
```

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
```suggestion
  await icapclient.processFiles(inPath, outputPath);
```

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
```suggestion
  await icapclient.processFiles(inPath, outputPath);
```

2021-02-11 15:37 UTC, werzl commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
```suggestion
  await icapclient.processFiles(inPath, outputPath);
```

2021-02-11 15:37 UTC, werzl commented on src/pages/policy.page.js
> +    I.say('Rows count is '+numberOfRecordsOfPolicy)
can use a template literal here

```suggestion
    I.say(`Rows count is ${numberOfRecordsOfPolicy}`)
```

2021-02-11 15:37 UTC, werzl commented on src/pages/policy.page.js
> +    let countSelection = `//li[contains(.,'`+ itemCount +`')]`
can use a template literal here

```suggestion
    let countSelection = `//li[contains(.,'${itemCount}')]`
```

2021-02-11 15:37 UTC, werzl commented on src/pages/policy.page.js
> +        assert.fail('The number of records displayed '+itemsCount+ ' is not as expected')
can use a template literal here

```suggestion
        assert.fail(`The number of records displayed ${itemsCount} is not as expected`)
```

2021-02-11 15:37 UTC, werzl commented on src/utils/steps_file.js
> +                    output.print('The response hearder is not available')
```suggestion
                    output.print('The response header is not available')
```

2021-02-11 15:37 UTC, werzl commented on codecept.conf.js
> +        //args: ['--no-sandbox', '--window-size=1536,826','--ignore-certificate-errors'],
Suggestion, maybe for another time, but you could pass in --headless in the environment variables, so this would become:

```suggestion
        //args: [process.env.headless, '--no-sandbox', '--window-size=1536,826','--ignore-certificate-errors'],
```

then, the env variable in the OS could be '--headless' or ''

2021-02-11 15:42 UTC, NadHodeGW commented on specs/icapserver_test.js
> +    var outputPath = './output/downloads'
Yes true, improved

2021-02-11 15:43 UTC, NadHodeGW commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
Done

2021-02-11 15:43 UTC, NadHodeGW commented on specs/icapserver_test.js
> +const { I, policyPage, filedropPage, requesthistoryPage, sharepoint,icapclient } = inject();
Done

2021-02-11 16:03 UTC, NadHodeGW commented on specs/icapserver_test.js
> +  await icapclient.processFiles(inPath,outputPath);
Done

2021-02-11 16:04 UTC, NadHodeGW commented on codecept.conf.js
> +        //args: ['--no-sandbox', '--window-size=1536,826','--ignore-certificate-errors'],
Done

2021-02-12 16:32 UTC, werzl approved these changes

2021-02-17 15:15 UTC, merged