Added more feature and steps in policy history Feature-627
filetrust/icap-management-ui-tests pull request #56
Opened 2020-10-26 18:46 UTC by jaind1046

Added more feature and steps in policy history Feature-627

2020-10-26 19:58 UTC, NadHodeGW commented on specs/features/content-management-policy-editing.feature
>          When the user presses the Cancel button
Please use I instead of "the user"

2020-10-26 20:01 UTC, NadHodeGW requested changes
see comment

2020-10-27 05:22 UTC, jaind1046 commented on specs/features/content-management-policy-editing.feature
>          When the user presses the Cancel button
Done. Replaced all. Will take care of this in the future also. Thanks.

2020-10-27 13:26 UTC, jaind1046 commented
@NadHodeGW It has all Scenario of issues-20 except TODO in the code with the upcoming PR with POLICY history test cases.

2020-10-27 16:39 UTC, NadHodeGW requested changes
Please add any required data in the corresponding scenario as example tables rather than putting them in the step's file

2020-10-27 16:56 UTC, jaind1046 commented
> Please add any required data in the corresponding scenario as example tables rather than putting them in the step's file

Hi Nadege.
These are data As User is giving "Embedded Files" in his own language in feature file .
But at the application page object we are putting field "embeddedFiles" as it is map with key as non space string. So there should be a mapping between those.
If you want me to remove these mapping than in featurte file every where these variables should be in camel case in which case we use to put variable in code.

2020-10-27 17:46 UTC, jaind1046 commented
> Please add any required data in the corresponding scenario as example tables rather than putting them in the step's file

@NadHodeGW Updated as per your comments also added the test case for policy history.

2020-10-27 18:04 UTC, NadHodeGW approved these changes

2020-10-27 18:04 UTC, merged