Adding policy preview screen
filetrust/icap-management-ui-tests pull request #59
Opened 2020-10-28 15:17 UTC by jaind1046

Adding policy preview screen

2020-10-28 19:20 UTC, NadHodeGW requested changes
See comments

2020-10-28 19:20 UTC, NadHodeGW commented on src/pages/policy.page.js
> +    const element = this.table.viewPolicyFirst;
The element "view" is a button, please update it back to previous state

2020-10-28 19:20 UTC, NadHodeGW commented on src/pages/policy.page.js
> +    const element = this.table.activatePolicyFirst;
The element "activate" is a button, please update it back to previous state

2020-10-28 19:20 UTC, NadHodeGW commented on specs/features/content-management-previous-policy.feature
>      @TEST-154
please remove this scenario 154, not required

2020-10-28 19:20 UTC, NadHodeGW commented on specs/features/content-management-previous-policy.feature
> +        Given I click on Policy History in the navigation panel
this should be changed to: 'Given I am on the Policy History page' to be in line with the other feature files

2020-10-29 12:38 UTC, jaind1046 commented on src/pages/policy.page.js
> +    const element = this.table.viewPolicyFirst;
Agree. Done.

2020-10-29 12:39 UTC, jaind1046 commented on specs/features/content-management-previous-policy.feature
>      @TEST-154
Done. tnanks.

2020-10-29 12:39 UTC, jaind1046 commented on src/pages/policy.page.js
> +    const element = this.table.activatePolicyFirst;
Done thanks.

2020-10-29 12:40 UTC, jaind1046 commented
@NadHodeGW Incorporated the comments. Thanks.

2020-10-29 16:33 UTC, NadHodeGW approved these changes

2020-10-29 16:53 UTC, jaind1046 commented on specs/features/content-management-previous-policy.feature
> +        Given I click on Policy History in the navigation panel
Done thanks.

2020-10-29 16:53 UTC, merged