request-history-filtering-by-risk-outcome
filetrust/icap-management-ui-tests pull request #60
Opened 2020-10-28 19:01 UTC by annachemic

2020-10-28 19:29 UTC, NadHodeGW requested changes
See requested changes in files

2020-10-28 19:29 UTC, NadHodeGW commented on specs/features/request-history-filtering-by-file-type.feature
> +    Scenario Outline: I am able to filter the risks log
I updated this to "I can filter the log by file type", i'm not sure why it's changed back; please use the latest master to see latest changes & revert this back to previous state.

2020-10-28 19:29 UTC, NadHodeGW commented on specs/features/request-history-filtering-by-file-type.feature
> -        When I click on the Add Filter button and add a file type filter as <filter>
Same as above, please revert back to previous state

2020-10-29 16:53 UTC, annachemic commented on src/pages/request-history.page.js
> +    fileTypeDoc: "div[class*='PopupFilter_inner__'] >  fieldset:nth-child(1) > div > label:nth-child(1) > span:nth-child(1) > span > input",
@NadHodeGW I know these locators look crazy but there is no ids or specific locators at all
Now it works with it using https://k8-proxy.github.io/request-history page

2020-10-29 16:53 UTC, annachemic commented on src/pages/request-history.page.js
> +  clickNext() {
a typo, I assume

2020-10-29 16:55 UTC, NadHodeGW approved these changes

2020-10-29 16:55 UTC, merged