Policy application to files screen test steps and feature
filetrust/icap-management-ui-tests pull request #61
Opened 2020-10-29 13:30 UTC by jaind1046

Policy application to files screen test steps and feature

2020-10-29 17:09 UTC, NadHodeGW requested changes
Please see comments in step file

2020-10-29 17:09 UTC, NadHodeGW commented on specs/step_definitions/content-management-policy-application-to-files.steps.js
> +const {
This test will fail, there is no login step

2020-10-29 17:09 UTC, NadHodeGW commented on specs/step_definitions/content-management-policy-application-to-files.steps.js
> +    policyPage.setFlagTypeForGivenContentFlagsForGivenDocType("embeddedFiles", fileType, flagType)
embeddedFiles is used as data but not in the scenario table

2020-10-29 17:09 UTC, NadHodeGW commented on specs/step_definitions/content-management-policy-application-to-files.steps.js
> +// TODO implement when functionality available
the file hashes for the original file and the rebuilt will both need to be provided in the scenario table for assertion

2020-11-01 13:36 UTC, jaind1046 commented on specs/step_definitions/content-management-policy-application-to-files.steps.js
> +// TODO implement when functionality available
Deleting this PR to raise new which has all changes according to the comments also.

2020-11-01 13:36 UTC, closed without merging

2020-11-01 13:36 UTC, jaind1046 commented
rasing new one.