@TEST-155 test case fix along with review comments
filetrust/icap-management-ui-tests pull request #73
Opened 2020-11-04 08:18 UTC by jaind1046

@TEST-155 test case fix along with review comments

@TEST-Change-all-content-flag-to-sanitise-for-all-doc-type --> it not given sanitise in the scenario file as it is already covered in @TEST-155

2020-11-04 08:19 UTC, jaind1046 commented
![Uploading TEST-155.png…]()

2020-11-04 08:20 UTC, jaind1046 commented
As the video was big in size to upload, So uploaded the screenshot of test cases run on local.

2020-11-04 08:21 UTC, jaind1046 commented
<img width="1251" alt="TEST-155" src="https://user-images.githubusercontent.com/69156488/98086505-e297c880-1ea4-11eb-85d8-b26071513811.png">

2020-11-04 09:10 UTC, NadHodeGW requested changes
comment in file

2020-11-04 09:10 UTC, NadHodeGW commented on specs/features/content-management-policy-editing.feature
> +    @TEST-Change-all-content-flag-to-sanitise-for-all-doc-type
Please make these 2 scenarios: "all-content-flag-to-sanitise" & "all-content-flag-to-disallow" into one and add the result column for saved flags

2020-11-04 10:29 UTC, jaind1046 commented
<img width="1233" alt="change all content flag" src="https://user-images.githubusercontent.com/69156488/98100339-bab16080-1eb6-11eb-9149-ec7ad96a7381.png">

2020-11-04 10:30 UTC, jaind1046 commented on specs/features/content-management-policy-editing.feature
> +    @TEST-Change-all-content-flag-to-sanitise-for-all-doc-type
Done. Thank you.

2020-11-04 17:04 UTC, jaind1046 commented
<img width="1241" alt="TEST-188-updated" src="https://user-images.githubusercontent.com/69156488/98142459-d3893880-1eed-11eb-8b77-25f246d4c88a.png">

2020-11-04 17:04 UTC, jaind1046 commented
Tested TC-188 after cahnge

2020-11-06 09:45 UTC, NadHodeGW approved these changes

2020-11-06 09:45 UTC, merged