content-management-policy-application-to-files issues-18
filetrust/icap-management-ui-tests pull request #83
Opened 2020-11-10 12:22 UTC by jaind1046

<img width="1253" alt="Policy-application-to-file" src="https://user-images.githubusercontent.com/69156488/98673557-812c9980-237d-11eb-8b90-227bd0e640f5.png">

2020-11-12 12:08 UTC, NadHodeGW requested changes
Please see comment in files

2020-11-12 12:08 UTC, NadHodeGW commented on specs/step_definitions/content-management-policy-application-to-files.steps.js
> +    I.uploadFileWithNoSanitiseData(`output/downloads/${file.trim()}`)
where is assertion here that shows the file outcome?

2020-11-12 12:08 UTC, NadHodeGW commented on src/utils/steps_file.js
> +            this.dontSeeElement(filedropPage.sections.analysisReportView)
why are you putting assertions in the step file? please remove any i.see or dont see from here. also, in function  uploadFileWithNoSanitiseData what are you trying to check by saying: this.dontSeeElement(filedropPage.sections.analysisReportView)?

2020-11-16 16:40 UTC, jaind1046 commented on src/utils/steps_file.js
> +            this.dontSeeElement(filedropPage.sections.analysisReportView)
Removed this dontSeeElement instead of it just clicked the download.

2020-11-16 16:40 UTC, jaind1046 commented
https://drive.google.com/file/d/1Du_ZskBIHQlBgXewRD-TvswF6eTAQlsg/view?usp=sharing

2020-11-16 18:29 UTC, NadHodeGW approved these changes

2020-11-16 18:32 UTC, merged