Test 217 test case correction
filetrust/icap-management-ui-tests pull request #90
Opened 2020-11-13 14:15 UTC by jaind1046

https://drive.google.com/file/d/1G4ILh9vvLGMtoebB9VZCadU-mXN-k_k_/view?usp=sharing

2020-11-16 15:42 UTC, jaind1046 commented
https://drive.google.com/file/d/1tx-sN-fKomqBvnqrHj53Bp97D5WQCV-s/view?usp=sharing

2020-11-16 16:35 UTC, NadHodeGW requested changes
see comment in feature file

2020-11-16 16:35 UTC, NadHodeGW commented on specs/features/content-management-policy-history.feature
> +            | itemCount |
nothing set in the fileCount how is this checked?

2020-11-16 16:48 UTC, jaind1046 commented on specs/features/content-management-policy-history.feature
> +            | itemCount |
This is not required as itemCount which we are setting will also work for the assertion. Please see the recording also.

2020-11-17 12:21 UTC, NadHodeGW requested changes
see comments in files

2020-11-17 12:21 UTC, NadHodeGW commented on specs/step_definitions/content-management-policy-history.steps.js
> -    policyPage.assertNumberOfRecordsOfPolicy(count)
only navigation action should be inside this Given step.

2020-11-17 12:21 UTC, NadHodeGW commented on src/pages/policy.page.js
> +        I.seeNumberOfElements(this.table.tableRows, itemCount)
if this records > itemCount is not the case then what happens? please revisit

2020-11-17 14:04 UTC, jaind1046 commented
<img width="1262" alt="Test-217 after changed assersion strategy" src="https://user-images.githubusercontent.com/69156488/99399566-dcc1ce80-290b-11eb-9e25-b9a81eb4fba4.png">

2020-11-18 19:36 UTC, NadHodeGW approved these changes

2020-11-18 19:36 UTC, merged